server:
  # ?????????
  port: 8100

spring:
  security:
    oauth2:
      # ???????
      resourceserver:
        jwt:
          # Jwt?claims?iss??????jwt????????????????
          # ?????????????????????????jwt
          issuer-uri: http://192.168.3.173:8080
